
scalar DateTime
scalar BufferType

type Query {
  getAllData(device_name: String!): [DeviceUp]
  getDataInRange(device_name: String!, start_date_utc: DateTime!, end_date_utc: DateTime!): [DeviceUp]
}

type DeviceUp {
  id: ID
  received_at: DateTime
  dev_eui: BufferType
  device_name: String
  application_id: Int
  application_name: String
  frequency: Int
  dr: Int
  adr: Boolean
  f_cnt: Int
  f_port: Int
  tags: String
  data: BufferType
  rx_info: BufferType
  object: BufferType
}